### ISSUE TITLE
A merge of two external databases

### ISSUE THREAD

**Issue by richardrowe** [pboehm/django-data-migration#11]
pboehm, great performance improvements with the latest patch, thanks!

I have a [probably relatively unique case] where I have two external databases sharing the same legacy schema and would like to run the migration script twice, merging into one. Would it make sense to allow database credentials, or even a 'profile' argument through the management command?

**Comment by pboehm** [comment]
I would rather suggest that you override the `migrate()`-method in your Migration where you configure the database access for the first db than calling super(...).migrate(...). Change the config for db access and call super (...).migrate(...) again.

It could be necessary to delete the AppliedMigration instance after the first migrate() call.

You can implement this behavior in your BaseMigration so that it is used by all inheriting migrations.
